RSE-Sheffield/SORT

SORT/settings.py

https://docs.djangoproject.com/en/5.1/topics/i18n/

Set locale options

---

home/models.py
home/services/project.py
home/templates/organisation/create.html
home/templates/organisation/organisation.html
home/templates/projects/edit.html
home/templates/projects/project.html
home/views.py
static/css/base.css
static/templates/base.html
static/templates/footer.html
survey/templates/survey/survey.html

- A few UI fixes to the `organisation` and `projects` pages
- Added description tags to projects
- Added edit button functionality to projects
- Fixed a bug in project services
- Fixed footer location

More UI/improvements

---

SORT/settings.py
docs/deployment.md

This allows us to view the Django error logs in detail when deployed as a service on the virtual machiens.
See: https://docs.djangoproject.com/en/5.1/topics/logging/
Changes:
- Configure Django logging

Set up Django logging

---

.github/workflows/check-gunicorn-config.yaml
config/systemd/gunicorn.service
gunicorn.conf.py

Changes:
- Added Gunicorn config file
- Added automatic checks for those settings

Add Gunicorn config file

---

deploy.sh
docs/deployment.md

Changes:
- Create and set permissions for the environment file `.env`

Add .env file to deployment script

---

data/survey_config/demography_only_config.json
survey/services/survey.py
survey/templates/survey/survey.html
survey/urls.py
survey/views.py

- Add survey mock response generator
- Add some example demographic questions

feat: add mock response generator

---

README.md
data/README.md

I fixed the readme so it accurately describes how to get the local development environment running.

Update developer setup docs

---

assets/sort-survey-configurator/src/lib/components/SurveyConfigurator.svelte
assets/sort-survey-configurator/src/lib/components/input/InputComponent.svelte
assets/sort-survey-configurator/src/lib/components/input/Radio.svelte
assets/sort-survey-configurator/src/lib/components/input/SectionComponent.svelte
assets/sort-survey-configurator/src/lib/misc.svelte.ts

- Can drag and drop field onto each other to reorder them in the configurator
- Can drag and drop field to other sections

feat: Add drag drop field re-ordering

---

config/nginx/gunicorn.conf

See issue https://github.com/RSE-Sheffield/SORT/issues/152 for the motivation for proposing this change.
Changes:
- Disable compressed responses in nginx

Disable nginx gzip

---

data/survey_config/sort_only_config.json
survey/services/survey.py
survey/views.py

Resolves #178 
- Prefix `Our organisation` to all questions
- Sort question scale changed to 1-5 (strongly disagree to strongly agree)
- Fix survey config permission error bug
Example of what the change looks like:

Re-phrase sort questions and change scale

---

.github/workflows/django-check.yaml
.gitignore
requirements-dev.txt

https://docs.djangoproject.com/en/5.1/topics/testing/advanced/#integration-with-coverage-py

Add coverage reporting

---

survey/services/survey.py

See issue https://github.com/RSE-Sheffield/SORT/issues/182

Add an empty "sections" key when creating a new survey

---

home/services/organisation.py
home/services/project.py

This should prevent awkward bugs
More info: https://docs.python-guide.org/writing/gotchas/#mutable-default-arguments

Remove mutable function arguments

---

.github/workflows/validate-json.yaml

Changes
- Add GitHub Actions workflow to check that data files are valid JSON (doesn't check schema)

Validate JSON files

---

deploy.sh

Added NPM installation and build step to deployment workflow.

Deploy NPM package

---

deploy.sh

Build Vite in the correct dir

---

.github/workflows/validate-json.yaml

Fix GH Actions workflow syntax

---

.github/workflows/lint-python.yaml
SORT/settings.py
home/admin.py
home/management/commands/clear_orphaned_files.py
home/models.py
home/services/__init__.py
home/services/organisation.py
home/services/project.py
home/templatetags/vite_integration.py
home/tests/model_factory.py
home/tests/test_services.py
home/views.py
survey/admin.py
survey/models.py
survey/services/survey.py
survey/tests/test_models.py
survey/urls.py
survey/views.py

I ran isort, black, and flake8 on everything (except migrations).
Resolves https://github.com/RSE-Sheffield/SORT/actions/runs/14618964287/job/41013740713

Apply code formatting and fix linting errors

---

deploy.sh

resolves
https://github.com/RSE-Sheffield/SORT/actions/runs/14618964325/job/41013739505

Remove unused variable

---

SORT/settings.py

Remove settings from settings.py

---

config/systemd/gunicorn.service

https://www.freedesktop.org/software/systemd/man/latest/systemd.exec.html#ReadWritePaths=

Replace deprecated systemd option

---

.github/workflows/lint-python.yaml

Only run the auto-code-pedantry-bot on dev branch

Auto-create PRs: target dev

---

SORT/settings.py
config/systemd/gunicorn.service
deploy.sh
docs/deployment.md

Fix for bug https://github.com/RSE-Sheffield/SORT/issues/226

Create media folder on deployment

---

survey/tests/test_invitation_views.py
survey/tests/test_survey_views.py

Fix test case class names

---

eslint.config.js
survey/templates/survey/report.html
ui_components/src/assets/grab_dots.svg
ui_components/src/lib/components/SurveyConfigurator.svelte
ui_components/src/lib/components/SurveyDataView.svelte
ui_components/src/lib/components/SurveyResponseComponent.svelte
ui_components/src/lib/components/input/Checkbox.svelte
ui_components/src/lib/components/input/InputComponent.svelte
ui_components/src/lib/components/input/Likert.svelte
ui_components/src/lib/components/input/LikertItem.svelte
ui_components/src/lib/components/input/LikertRow.svelte
ui_components/src/lib/components/input/Radio.svelte
ui_components/src/lib/components/input/SectionComponent.svelte
ui_components/src/lib/components/input/Select.svelte
ui_components/src/lib/components/input/Text.svelte
ui_components/src/lib/components/input/TextArea.svelte

- This fixes the issue that involves dragging over text when editing field properties.
- Fields change background to highlight being dragged over

Use drag handle instead of entire div for drag event

---

home/views.py

Resolves bug:
- https://github.com/RSE-Sheffield/SORT/issues/288

Fix invitation permissions code

---

data/survey_config/demography_only_config.json

Changes:
- Added "Please describe your current role"
- Added "Please provide your job title"
- Added "How many years have you been qualified"

Add new demographics questions

---

survey/models.py
survey/services/survey.py
ui_components/src/lib/components/input/TextArea.svelte

**Changes**
- Refactored CSV generation code
* Use `csv.DictWriter` instead of `csv.writer` to try to improve data integrity
* Generate rows of survey data using separate methods on `Survey` and `SurveyResponse`
- Fixed(?) the `TextArea` field so it doesn't produce undefined responses for empty text fields

Refactor CSV export code

---

home/checks/__init__.py
survey/services/survey.py

Minor tweaks
https://github.com/RSE-Sheffield/SORT/actions/runs/16344618571/job/46175061009

Fix linting errors

---

.flake8
.github/workflows/lint-python.yaml
home/checks/__init__.py
survey/services/survey.py

We should run the linter on PRs that we propose to merge, not just on new commits in dev.
The linting errors are fixed in this PR:
- https://github.com/RSE-Sheffield/SORT/pull/330

Lint on PR into dev

---

survey/management/commands/csv.py
survey/management/commands/csv_fix.py
survey/models.py
survey/services/survey.py
survey/tests/test_invitation_views.py
survey/tests/test_survey_service.py
survey/tests/test_survey_views.py

changes:
- move the survey config merge to a separate method that can be called without the survey service
includes
- https://github.com/RSE-Sheffield/SORT/pull/358

Fix CSV export

---

home/models.py
home/templates/organisation/organisation.html
survey/models.py

Fix a bug that breaks the My Organisation page.
**Changes**
- Revert a change to a field name that I made that broke the "My Organisation page"
Source of the bug:
https://github.com/RSE-Sheffield/SORT/commit/ccdbd31b1597d0921453f416a05f7220ed9b8510#diff-9f5820fc3dba422f9cfdbca535d7f2c2c0c3584be53330ab5f46a099e5241664

Revert a change that broke things

---

home/templates/home/welcome.html

Update welcome page text

---

requirements.txt

Resolves 
- https://github.com/RSE-Sheffield/SORT/security/dependabot/27
- CVSS:3.1/AV:N/AC:H/PR:L/UI:N/S:C/C:H/I:L/A:N
Release notes
https://docs.djangoproject.com/en/5.2/releases/5.1.13/

Upgrade Django to avoid SQL injection vulnerability

---

.gitignore
home/templates/home/privacy.html
home/urls.py
home/views.py
static/templates/footer.html

Resolves https://github.com/RSE-Sheffield/SORT/issues/394
Added a privacy notice page at `/privacy`
Footer link:
Screenshot:

Add privacy notice

---

survey/views.py

Resolves
- https://github.com/RSE-Sheffield/SORT/security/code-scanning/4
- https://github.com/RSE-Sheffield/SORT/security/code-scanning/3

Remove referrer redirect
